version: '3.1'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '7000:7000'
    depends_on:
      - books_db

  books_db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"